version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=$DOCKER_HUB_REPO
      - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building application...
      - ./gradlew build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:producer-latest-develop -f docker/dev.Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:producer-latest-develop
reports:
  JacocoReport:
    files:
      - '**/*'
    base-directory: build/test-results/test
cache:
  paths:
    - '.gradle/wrapper/**/*'